# -*- coding: utf-8 -*-
"""estudos_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAQc5YB-_Sxx6Ak-meHgdIASf1gmXgOB
"""

## Desafio DIO - sistema banácrio
import random
import time
from datetime import date

saldo_inicial = saldo = random.randint(1, 1001)
deposito_cont = 0
saque_cont = 0
while True:
  print("====================")
  print("      BANCO DIO       \n Escolha a operação: \n 1 - Deposito \n 2 - Saque \n 3 - Extrato \n 4 - Encerrar")
  print("====================")
  opc = int(input("Sua resposta: "))
  if opc == 1:
    print(f"Seu saldo atual é: {saldo}.")
    time.sleep(1.5)
    deposito = int(input("Informe o valor do deposito: "))
    print("Processando...")
    time.sleep(1.5)
    deposito_cont += deposito
    saldo += deposito
    print(f"Operação realizada com sucesso. Seu novo saldo é de {saldo}. \n")
    time.sleep(1.5)
  if opc == 2:
    print(f"Seu saldo atual é: {saldo}.")
    saque = int(input("Quanto deseja sacar? "))
    time.sleep(1)
    print("Processando...")
    time.sleep(1)
    saque_cont += saque
    saldo -= saque
    print(f"Operação realizada com sucesso. Seu novo saldo é: {saldo}. \n")
  if opc == 3:
    data = int(input("Extrato do dia atual ou outra data? \n 1 - Dia atual \n 2 - Outra data \n Resposta: "))
    if data == 1:
      print("____________________")
      print(f"Saldo inicial: {saldo_inicial} \n ------------------ \n Entradas: {deposito_cont} \n Saídas: {saque_cont} \n ------------------ \n Saldo final: {saldo}.")
      print("____________________")
    if data == 2:
      data = str(input("Informe a data (DD/MM/AAAA): "))
      random_SI = random.randint(1, 1001)
      random_in = random.randint(1, 1001)
      random_out = random.randint(1, 1001)
      random_SF = (random_SI + random_in) - random_out
      print("____________________")
      print(f"Saldo inicial: {random_SI} \n ------------------ \n Entradas: {random_in} \n 3Saídas: {random_out} \n ------------------ \nSaldo final: {random_SF}.")
      print("____________________")
  if opc == 4:
    break
  next = int(input("Deseja continuar? \n 1 - Sim \n 2 - Não \n Resposta: "))
  if next == 2:
    break
  else:
    continue