# -*- coding: utf-8 -*-
"""pacote_OP_MAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8jigmGc4icLyoEtTMFUqwRf9CP2_EX_
"""

math_operations/
    __init__.py
    operations.py
    README.md
    setup.py

# operations.py

def adicionar(a, b):
    """Retorna a soma de dois números."""
    return a + b

def subtrair(a, b):
    """Retorna a subtração de dois números."""
    return a - b

def multiplicar(a, b):
    """Retorna a multiplicação de dois números."""
    return a * b

def dividir(a, b):
    """Retorna a divisão de dois números. Levanta uma exceção se b for zero."""
    if b == 0:
        raise ValueError("Divisão por zero não é permitida.")
    return a / b

# __init__.py

from .operations import adicionar, subtrair, multiplicar, dividir

# Math Operations Package

Este pacote oferece operações matemáticas básicas como adição, subtração, multiplicação e divisão.

## Como usar

```python
from math_operations import adicionar, subtrair, multiplicar, dividir

print(adicionar(5, 3))  # 8
print(subtrair(10, 7))  # 3
print(multiplicar(4, 2))  # 8
print(dividir(9, 3))  # 3.0

# setup.py

from setuptools import setup, find_packages

setup(
    name="math_operations",
    version="0.1",
    description="Um pacote simples para operações matemáticas básicas",
    author="JOAO PEDRO STENIO",
    packages=find_packages(),
    install_requires=[],  # Não há dependências externas
)